# Generated by Django 4.2.4 on 2023-08-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_main_title', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='page_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ('main_title',), 'verbose_name_plural': 'HomePageItems'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
