# Generated by Django 4.2.4 on 2023-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepageabout_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='page_images/features_icons')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageFeaturesTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('second_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='homepagecard',
            name='card_image',
            field=models.ImageField(upload_to='page_images'),
        ),
    ]
