# Generated by Django 4.2.4 on 2023-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepagefeatures_homepagefeaturestitles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeatures',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
