# Generated by Django 4.2.4 on 2023-08-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_homepagefeatures_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_images/team')),
                ('full_name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('telegram_link', models.CharField(max_length=255, null=True)),
                ('facebook_link', models.CharField(max_length=255, null=True)),
                ('linkedin_link', models.CharField(max_length=255, null=True)),
                ('twitter_link', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageTeamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
