# Generated by Django 4.2.4 on 2023-08-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepageteam_homepageteamtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMembers',
        ),
    ]
