# Generated by Django 4.2.4 on 2023-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homepagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_images/service_images')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='HomePageFeaturesTitles',
            new_name='HomePageServicesTitle',
        ),
        migrations.DeleteModel(
            name='HomePageFeatures',
        ),
    ]
